### ISSUE TITLE
Unable to import UML profile

### ISSUE THREAD

**Issue by haritrichy** [mhavey/marklogic#6]
Hi,
I followed your blog [http://developer.marklogic.com/blog/uml-modeling-marklogic-entity-services](url) and tried to import UML profile in MagicDraw 18.5 (File menu -> Import From -> MagicDraw Native XML file. Unfortunately, I received the following error. Could you please help? Thanks

com.nomagic.magicdraw.persistence.xmi.load.model.utils.a
	at com.nomagic.magicdraw.persistence.ProjectLoadService.load(ProjectLoadService.java:308)
	at com.nomagic.magicdraw.persistence.ProjectLoadService.load(ProjectLoadService.java:252)
	at com.nomagic.magicdraw.persistence.ProjectLoadService.loadAndHandleErrors(ProjectLoadService.java:122)
	at com.nomagic.magicdraw.persistence.ProjectLoadService$1.execute(ProjectLoadService.java:191)
	at com.nomagic.task.Task.construct(Task.java:191)
	at com.nomagic.task.SwingWorker$2.call(SwingWorker.java:213)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.nomagic.task.SwingWorker$SwingWorkerFuture.run(SwingWorker.java:602)
	at com.nomagic.task.BackportedThreadPoolExecutor$Worker.runTask(BackportedThreadPoolExecutor.java:1583)
	at com.nomagic.task.BackportedThreadPoolExecutor$Worker.run(BackportedThreadPoolExecutor.java:1614)
	at com.nomagic.task.PooledThread.run(PooledThread.java:64)

**Comment by mhavey** [comment]
I was able to load the profile into my instance of MagicDraw 18.5. Let's verify two things:

1. Your exact version of MagicDraw. Under Help menu, choose About MagicDraw. In the dialog box entitled "About", choose the Licensing tab. Can you share a screenshot of that please.
2. Which file are you loading? I recommend you the latest from my master branch. The file you want is marklogic/uml2es/umlProfile/magicdraw/MLProfile.xml.

To load the file in this way means you intend to update the profile, not use the profile in another model. Is that your intent?

**Comment by haritrichy** [comment]
1. Screenshot of licensing tab is below,
![screen shot 2018-10-28 at 8 28 30 am](https://user-images.githubusercontent.com/36141833/47615868-a3e80000-da8b-11e8-9720-9d601d75bc8e.png)

2. I tried to import again but faced the same error

I'd like to do both so I shall edit the profile if required.

To use your profile in another model, could u please share your instructions if possible? I wanted to ensure I follow the correct steps

Would really help if you could upload a video on both using as well as updating the profile. This modeling method would be very handy and we're trying our best to make this work. Thanks in advance

**Comment by mhavey** [comment]
I just tried with exactly the same MagicDraw build and did not get the error.  From the error you show, I'm thinking you are loading the profile marklogic/uml2es/umlProfile/MLProfile.xml. That is NOT a MagicDraw native file. You should instead load the profile marklogic/uml2es/umlProfile/magicdraw/MLProfile.xml.

Per your suggestion, I will post instructions on how to: (a) Open the profile in MagicDraw to edit it. (b) Create a new model in MagicDraw using the profile.

**Comment by haritrichy** [comment]
Thanks Mike. It works like gem now on MagicDraw. Would help if you could publish Eclipse or papyrus too. Since it's open-source, we'll start using that.

**Comment by haritrichy** [comment]
Tutorial to use the profile on MagicDraw explained the steps to follow and it resolved the problem.

**Comment by mhavey** [comment]
I will work on Papyrus tutorials. Please don't hesitate to ask questions or open issues as you progress with the toolkit.

**Comment by mhavey** [comment]
I'm working on it now. It will be ready by mid-next week at the latest.

**Comment by haritrichy** [comment]
Thank you

**Comment by mhavey** [comment]
A draft of the tutorials is available on the master branch under uml2es/tutorials.

**Comment by mhavey** [comment]
Some of the examples are modeled in MagicDraw, others in Papyrus. For running race and movie talk, I have included the Papyrus eclipse projects (including the di file). You can find them  at https://github.com/mhavey/marklogic/tree/master/uml2es/examples/movietalk/data/MovieTalkPapyrus and https://github.com/mhavey/marklogic/tree/master/uml2es/examples/runningRace/data/RunningRacePapyrus.  For the tutorials, I haven't included the Eclipse projects, but I will.
